<?php
$fonts = array(
    array(
        "name" => "zawgyi",
        "font_family" => "Zawgyi-One",
        "font_file" => "zawgyi.ttf",
        "font_file_eot"=> "zawgyi.eot",
        "support_mac" => true,
        "support_windows"=>true,
        "support_chrome" => true,
    ),
    array(
        "name" => "imon",
        "font_family" => "iMon",
        "font_file" => "iMon.ttf",
        "font_file_eot"=> "iMon.eot",
        "support_mac" => true,
        "support_windows"=>true,
        "support_chrome" => true,
    ),
    array(
        "name" => "mon3",
        "font_family" => "MON3 Anonta 1",
        "font_file" => "mon3.ttf",
        "font_file_eot"=> "mon3.eot",
        "support_mac" => true,
        "support_windows"=>true,
        "support_chrome" => true,
    ),
    array(
        "name" => "myanmar3",
        "font_family" => "Myanmar3",
        "font_file" => "myanmar3.ttf",
        "font_file_eot"=> "myanmar3.eot",
        "support_mac" => true,
        "support_windows"=>true,
        "support_chrome" => true,
    ),
    array(
        "name" => "yunghkio",
        "font_family" => "Yunghkio",
        "font_file" => "yunghkio.ttf",
        "font_file_eot"=> "yunghkio.eot",
        "support_mac" => false,
        "support_windows"=>true,
        "support_chrome" => true,
    ),
    array(
        "name" => "masterpiece",
        "font_family" => "Masterpiece Uni Sans",
        "font_file" => "masterpiece.ttf",
        "font_file_eot"=> "",
        "support_mac" => true,
        "support_windows"=>false,
        "support_chrome" => false,
    ),
    array(
        "name" => "padauk",
        "font_family" => "Padauk",
        "font_file" => "padauk.ttf",
        "font_file_eot"=> "padauk.eot",
        "support_mac" => false,
        "support_windows"=>true,
        "support_chrome" => true,
    ),
    array(
        "name" => "mymyanmar",
        "font_family" => "MyMyanmar Universal",
        "font_file" => "MyMMUnicodeUniversal.ttf",
        "font_file_eot"=> "MyMMUnicodeUniversal.eot",
        "support_mac" => true,
        "support_windows"=>true,
        "support_chrome" => true,
    ),
    array(
        "name" => "unimon",
        "font_family" => "Uni Mon",
        "font_file" => "unimon.ttf",
        "font_file_eot"=> "unimon.eot",
        "support_mac" => true,
        "support_windows"=>true,
        "support_chrome" => true,
    ),
    array(
        "name" => "oursunicode",
        "font_family" => "Ours-Unicode",
        "font_file" => "oursunicode.ttf",
        "font_file_eot"=> "oursunicode.eot",
        "support_mac" => true,
        "support_windows"=>true,
        "support_chrome" => true,
    )
    );
